spring:
  boot:
    admin:
      ui:
        cache-templates: true
  output:
    ansi:
      enabled: always
  
server:
  port: 10100
   
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: 
    path: "/var/log"
    name: ${spring.application.name}.log
  level:
    root: INFO 

